USE [master]
GO

/****** Object:  Database [Cuzdan]    Script Date: 1/18/2022 4:21:21 PM ******/
CREATE DATABASE [Cuzdan]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cuzdan', FILENAME = N'C:\cuzdan_db\Cuzdan.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cuzdan_log', FILENAME = N'C:\cuzdan_db\Cuzdan_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cuzdan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cuzdan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cuzdan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cuzdan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cuzdan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cuzdan] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cuzdan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cuzdan] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Cuzdan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cuzdan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cuzdan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cuzdan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cuzdan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cuzdan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cuzdan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cuzdan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cuzdan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cuzdan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cuzdan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cuzdan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cuzdan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cuzdan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cuzdan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cuzdan] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cuzdan] SET  MULTI_USER 
GO

ALTER DATABASE [Cuzdan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cuzdan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cuzdan] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cuzdan] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Cuzdan] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Cuzdan] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Cuzdan] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Cuzdan] SET  READ_WRITE 
GO


