//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankuzef_Programlama_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int Id { get; set; }
        public int Hesap_No { get; set; }
        public string Hesap_Adi { get; set; }
        public Nullable<decimal> Alacak { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public string Aciklama { get; set; }
    }
}
